name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  vector:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make vector

  ubuild:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make vector

#     - name: configure
#       run: ./configure
#     - name: make check
#       run: make check
#     - name: make distcheck
#       run: make distcheck
