name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Macvector:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: make vec
      run: make vector
    - name: make map
      run: make map
    - name: make stack
      run: make stack

  Ubuntuvector:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make vec
      run: make vector
    - name: make map
      run: make map
    - name: make stack
      run: make stack

#     - name: configure
#       run: ./configure
#     - name: make check
#       run: make check
#     - name: make distcheck
#       run: make distcheck
